/* TypeScript file generated by genType. */

import LangBox from './LangBox';

import * as React from 'react';

// tslint:disable-next-line:no-var-requires
const ReasonReact = require('reason-react/src/ReasonReact.js');

// tslint:disable-next-line:interface-over-type-literal
export type Props = {readonly lang: string};

// In case of type error, check the type of 'make' in 'LangBoxRe.re' and the props of './LangBox'.
export function LangBoxTypeChecked(props: Props) {
  return <LangBox {...props}/>;
}

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make: unknown = function _(lang: any, children: any) { return ReasonReact.wrapJsForReason(LangBox, {lang: lang}, children); };
